version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  superset:
    image: apache/superset:latest
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - "8088:8088"
    volumes:
      - ./superset_home:/app/superset_home

  superset-init:
    image: apache/superset:latest
    depends_on:
      - db
      - redis
    command: >
      bash -c "pip install psycopg2-binary &&
              superset db upgrade &&
              superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
              superset init"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    volumes:
      - ./superset_home:/app/superset_home

volumes:
  redis:
  postgres: